// <auto-generated />
using System;
using CRUDApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDApplication.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20201231164721_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CRUDApplication.Models.Affectation", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DAffecation")
                        .HasColumnType("datetime2");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.HasKey("AId");

                    b.ToTable("Affecations");
                });

            modelBuilder.Entity("CRUDApplication.Models.Consultant", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CId");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("CRUDApplication.Models.Projet", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Psubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("PId");

                    b.ToTable("Projets");
                });
#pragma warning restore 612, 618
        }
    }
}
